### ISSUE TITLE
shinydisconnect closes window without showing message

### ISSUE THREAD

**Issue by charleswidnall** [daattali/shinydisconnect#10]
Hi Dean,

I'm trying to run _shinydisconnect_ in 3 Windows computers and, in each one of them, when I click on the "Disconnect the app" action button, each obediently closes the page but no message, box, or little window shows up. The page is just closed and I'm left with the "Listening on http://127.0.0.1:..." standard message. This happens with both _disconnectMessage_ and _disconnectMessage2_.

The _reprex_ is virtually the same as in the demo (I just added the library(shinydisconnect) statement).

```
  library(shiny)
  library(shinydisconnect)

  shinyApp(
    ui = fluidPage(
      disconnectMessage(),
      actionButton("disconnect", "Disconnect the app")
    ),
    server = function(input, output, session) {
      observeEvent(input$disconnect, {
        session$close()
      })
    }
  )
```

However, everything works well in the demo page: _https://daattali.com/shiny/shinydisconnect-demo/_

Would you have any suggestion to make it work or, at least, to try to find out what's wrong on my side?

Thanks,

CW

I'm using Chrome Version 98.0.4758.102 (Official Build) (64-bit) in my 3 Windows computers. The RStudio/Shiny/Windows versions are:

- 4.0.4/1.6.0/Windows 10
- 4.0.3/1.5.0/Windows 10
- 4.1.1/1.7.1/Windows 11

**Comment by daattali** [comment]
If `session$close()` closes the browser, that's not something controllabel by this package. What this package does is merely give a nice message instead of the default one. I'm not sure why this closes the browser for you but that's out of scope for shinydisconnect.

You can try to run a shiny app from RStudio and then click the red Stop button to kill the app - that should also generate the message. If this also results in the browser window closing for you, it must be some setting somewhere.
